version: "3.9"
services:
    web:
        build: .
        ports: 
            - 8081:8081
        volumes:
            - ./htdocs:/var/www/html/
            - ./sites-available:/etc/apache2/sites-available/
        networks:
            - network01
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_DATABASE: evoting
            MYSQL_USER: admin
            MYSQL_PASSWORD: psswrd
            MYSQL_ROOT_PASSWORD: Password1
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - volume01:/var/lib/mysql
        networks:
            - network01
networks:
    network01:
        driver: bridge
volumes:
    volume01:
        driver: local